<<<<<<< HEAD
# Generated by Django 4.1 on 2022-10-28 05:57
=======
# Generated by Django 4.1 on 2022-10-29 07:03
>>>>>>> b2ef0e0e204d5e196d91c8eeb97ff76d878f59b8

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
=======
import recycle.models
>>>>>>> b2ef0e0e204d5e196d91c8eeb97ff76d878f59b8


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=recycle.models.get_default_my_date)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> b2ef0e0e204d5e196d91c8eeb97ff76d878f59b8
            ],
        ),
    ]
