# Generated by Django 4.1 on 2022-10-29 07:56

from django.db import migrations, models
import recycle.models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=recycle.models.get_default_my_date),
        ),
    ]
