# Generated by Django 4.1 on 2022-10-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
