# Generated by Django 4.1 on 2022-11-01 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpage', '0002_barangwishlist_user_alter_barangwishlist_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangwishlist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
