# Generated by Django 4.1 on 2022-11-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_rename_barangwishlist_adminpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpage',
            old_name='harga_barang',
            new_name='email_admin',
        ),
        migrations.RenameField(
            model_name='adminpage',
            old_name='nama_barang',
            new_name='nama_admin',
        ),
    ]
