# Generated by Django 4.1 on 2022-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_barangwishlist_delete_taskadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangwishlist',
            name='harga_barang',
            field=models.TextField(),
        ),
    ]
