# Generated by Django 4.1 on 2022-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_alter_barangwishlist_harga_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
